
// const String baseUrl = "https://9263-103-223-15-43.ngrok-free.app/";
const String baseUrl = "https://api.projectplayapp.com/";
const String imageBaseUrl = "https://playpadelpickel.s3.eGIT u-north-1.amazonaws.com/";

const String logOutEndPoint = "api/user/logout";
const String signupEndPoint = "api/user-signup";
const String emailVerifyEndPoint = "api/verify-otp";
const String resendOtpEndPoints = "api/resend-otp";
const String loginEndPoints = "api/user-login";
const String forgetPasswordEndPoints = "api/user-forgot-password";
const String forgetOtpVerifyEndPoints ="api/verify-otp-forget-password";
const String resetEndPoints ="api/user-new-password-otp-verified";
const String myOderDetailEndPoints ="api/user/get-orders";
const String getHomeDataEndPoints ="api/user/user-home-screen";
const String fileUploadEndPoint ="api/user/upload-image";
const String updateProfileEndPoints ="api/user/update-user";
const String getVenuesDataEndPoints ="api/user/get-venues";
const String getUserByIdEndPoints ="api/user/get-friends-byId";
const String getRequestEndPoints ="api/user/get-friends";
const String confirmRequestEndPoints="api/user/request-action";
const String blockRequestEndPoints="api/user/block-user";
const String getAllUserEndPoints ="api/user/search-friend";
const String bookingEndPoints ="api/user/book-court";
const String JoinbookingEndPoints ="api/user/join-open-matches";
const String paymentEndPoints ="api/user/booking-payment";
const String courtInfoEndPoints="api/user/get-courts";
const String sendRequestEndPoints ="api/user/send-request";
const String socialLoginEndPoint ="api/social-login";
const String getProfileEndPoint ="api/user/get-user";
const String getMerchandiseEndPoint ="api/user/merchandise";
const String getBookingsEndPoints="api/user/my-matches?type=all";
const String getopenBookingsEndPoints="api/user/get-open-matches";
const String getAllBookingsEndPoints="api/user/my-matches?type=current";
const String cancelBooking="api/user/cancel-booking";
const String uploadScoreEndPoints ="api/user/upload-score";
const String getJoinBookingDetail ="api/user/open-matches-data-byId";
const String getChatMessages ="api/chat/get-chats";
const String getChatMessagesList ="api/chat";
const String MessageChatApi ="api/chat/message";
const String IndividualChatCreateApi ="api/chat/individual";
const String AddtocartApi ="api/user/cart";
const String OrderPostApi ="api/user/merchandise";
const String MyOrders ="api/user/get-orders";
const String ContentEndPoint ="api/user/application-info";
const String TransactionHistoryEndPoint ="api/user/user-transactions";
const String notificationsEndPoint ="api/user/user-notifications";
const String packagesEndPoint ="api/user/packages";
const String BookingDetailEndPoint ="api/user/my-matches";

